sudo: required
language: php
php:
  - 7.2
  - 7.3
  - 7.4snapshot

# block list
branches:
  except:
  - wip

services:
  - mysql

env:
  #- UNIT=1 CODE_COVERAGE=1 PREFER_LOWEST="--prefer-lowest" #composer can't resolve prefer-lowest in reasonable time
  - UNIT=1 CODE_COVERAGE=1 PREFER_LOWEST=""
  #- INTEGRATION=1 CODE_COVERAGE=1 PREFER_LOWEST="--prefer-lowest" #composer can't resolve prefer-lowest in reasonable
  #time
  - INTEGRATION=1 CODE_COVERAGE=1 PREFER_LOWEST=""

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - ./travis_before_install.sh

before_script:
  - ./travis_before_script.sh

script:
  - ./travis.sh