sudo: required
language: php
php:
  - 7.1
  - 7.2

# block list
branches:
  except:
  - wip

services:
  - mysql

env:
  - UNIT=1 CODE_COVERAGE=1 WITH_LOCK=1
  - UNIT=1 CODE_COVERAGE=1 WITH_LOCK=0
  - INTEGRATION=1 CODE_COVERAGE=1

matrix:
  exclude:
  - php: 7.1
    env: UNIT=1 CODE_COVERAGE=1 WITH_LOCK=1

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - ./travis_before_install.sh

before_script:
  - ./travis_before_script.sh

script:
  - ./travis.sh