sudo: required
language: php
php:
  - 7.1
  - 7.2

services:
  - mysql

env:
  - UNIT=1
  - INTEGRATION=1

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    php: 7.2
    env:
      - CODE_COVERAGE=1
      - UNIT=1
      - INTEGRATION=1

before_install:
  - ./travis_before_install.sh

before_script:
  - ./travis_before_script.sh

script:
  - ./travis.sh